### ISSUE TITLE
vytvorit kopiu prevadzkovaneho systemu

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2017/PritomnostNaPracovisku#1]
pre potreby vyvojoveho timu vytvorit kopiu systemu pouzivaneho na KAI na rovnakom prevadzkovom prostredi.

**Comment by pavelpetrovic** [comment]
kopia systemu bola vytvorena na http://kempelen.ii.fmph.uniba.sk/dochadzka/
pristupove udaje davam Marekovi Krafcikovi.

**Comment by krafcima** [comment]
vdaka, momentalne prebieha analyzovanie poskytnutých dát.
