### ISSUE TITLE
Zohnat vzory dokumentov

### ISSUE THREAD

**Issue by PatrikFurm** [TIS2017/PritomnostNaPracovisku#12]

**Comment by krafcima** [comment]
Zajtra budem komunikovať s pani Slobodovou, potom budem informovať o ďalšom priebehu.

**Comment by krafcima** [comment]
Ahojte, pracuje sa tom, dnes som sa stretol s p. Zuzanou Slobodovou a dohodli sme sa na vytvorení priečinka v googleDocs, kde nám ona nazdieľa vzory jednotlivých dokumetov, ktoré následne pridám na Git.
Kým ale nebudem hotový, nechám issue otvorený a založím na to issue.

**Comment by krafcima** [comment]
FYI,
Ahojte, 
podarilo sa získal som všetko čo je potrebné.
