### ISSUE TITLE
Vytvorenie návrhu

### ISSUE THREAD

**Issue by krafcima** [TIS2017/PritomnostNaPracovisku#15]
Ahojte, 
v tomto issue sa budeme venovať vytvoreniu návrhu.

**Comment by krafcima** [comment]
FYI,
Ahojte, 
dnes sme nahrali na Git Návrh, ktorý budeme konzultovať s cvičiacim v piatok.

**Comment by andrejjursa** [comment]
@TIS2017/unknowns  Pozrel som si zbezne dokument v branch Navrh, vidim, ze sa rozrasta o mnoho wireframov, tie treba vsak detailne popisat (netreba popisovat dokola opakujuce sa casti ako hlavicka a paticka ak sa nemenia).

Co mi robi starosti je dekompozicia, ktora ma teda daleko od uznania. Ako som na stretnuti hovoril, treba popisat triedy a ich metody (aj so vstupmi) a popisat, co kazda robi, s akou db tabulkou pracuje atd., taka ukazka (vseobecne, nevstahuje sa na vas projekt):

Trieda `User` - sluzi na spravu pouzivatelov, ma nasledujuce metody:
 - `public bool addUser(string firstName, string lastName, string login, string passwort)` - vlozi do tabulky `users` novy zaznam o pouzivatelovi, ak dany `login` uz existuje, vrati chybu (`false`)
 - `public array[User] getAllUsers(int pageSize, int page = 1)` - vrati `pageSize` pocet pouzivatelov z databazi na stranke `page`, ak je mimo rozsah, vrati `null`
 - ...

**Comment by krafcima** [comment]
FYI,
Ahojte, 
dnes sme nahrali na Git najaktuálnejšiu verziu návrhu, prosím, možete ho pozrieť, či to môže byť takto spravené a ak áno, tak to takto dokončíme, dôležitá je hlavne sekcia 4.2 - dekompozícia aplikácie,

Vďaka ;-)

**Comment by andrejjursa** [comment]
@TIS2017/unknowns ahojte, ano tak ako ste zacali pisat dekompoziciu to vyzera ok, len by som poprosil, aby ste boli konkretny, ked opisujete co, ktora metoda/konstruktor vola (iba volania v ramci vasho kodu), napr. Users konstruktor je pisane, ze vola potrebne metody, predpokladam, ze ide o nejake metody triedy Users, bolo by fajn napisat, ktore to su, ak vola metody/funkcie php, tak tie uvadzat netreba, iba ze by boli skutocne dolezite.

Pozrel som aj dalsie wireframy, ktore pribudli, dva su vykreslene s tlacidlami Submit v case, ked boli upravovane v editore, posobi to hrozne, prosim ak sa to da nahradte to obrazkami, kde tie tlacidla nebudu vykreslene takto. Dalsia vec co sa tyka formularov, pride mi sialene mat popisy policok vo formularoch iba v ich placeholderoch, plne vyplneny formular potom bude nejednoznacny co kam patri alebo aka informacia je vobec v ktorom policku. Bolo by dobre nakoniec formulare v aplikacii normalne oznacovat cez label (netvrdim, ze nemozu mat placeholder).

**Comment by krafcima** [comment]
FYI, 
Ahojte, 
v noci som nahral novú verziu návrhu s dokončenou dekompozíciou, prosím o feedback aby sme čo najskôr opravili prípadné nedostatky. 
Vďaka 
Marek

**Comment by krafcima** [comment]
FYI,
Ahojte,
nedostatky opravené.
