### ISSUE TITLE
je tu málo issues

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2017/PritomnostNaPracovisku#5]
to sa okrem katalógu požiadaviek na ničom nerobí?

vždy platí, že nie je možné robiť na projekte nič bez toho, aby na to nebol vytvorený issue! a komunikácia o tom, čo sa robí prebieha tu. napravte to a potom tento issue zatvorte, ďakujem.

**Comment by PatrikFurm** [comment]
Hotovo.
