### ISSUE TITLE
Test of rewieving pull requests into master branch 

### ISSUE THREAD

**Issue by krafcima** [TIS2017/PritomnostNaPracovisku#8]
We wanted to test uploading new version of Katalog-požiadaviek into a master branch

**Comment by krafcima** [comment]
I have tested it, everything is working fine.

**Comment by oliversabik** [comment]
odtestoval som si reviewing... je to ok

**Comment by PatrikFurm** [comment]
ok

**Comment by iHellino** [comment]
Done...
